name: Docker Image CI 

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-buildx-action@v1
    - name: Build the Docker image
      run: make ci
      #run: make build
      #run: make push
